import { FONT_STACKS, type PresetDefinition } from "./tokens";
import type { PresetId } from "./types";

/**
 * Seis identidades visuales completas. Cada una define su propio par
 * claro/oscuro — el selector de modo de color del visitante nunca deja un
 * preset a medias ni lo convierte en una pagina blanca generica.
 *
 * Ningun componente lee este archivo directamente: todo pasa por
 * lib/theme/resolve.ts, que vuelca estos valores en variables CSS.
 */
export const PRESETS: Record<PresetId, PresetDefinition> = {
  elegante: {
    id: "elegante",
    label: "Elegante",
    description: "Alta cocina clasica: vino, oro envejecido y serifa editorial.",
    radiusShape: "soft",
    fontDisplay: FONT_STACKS.serif,
    fontBody: FONT_STACKS.neutralSans,
    light: {
      bg: "#faf8f5",
      surface: "#ffffff",
      surfaceRaised: "#ffffff",
      border: "#e4ddd2",
      borderStrong: "#ccbfa8",
      text: "#1a1815",
      textMuted: "#6b655c",
      textFaint: "#a39c8f",
      primary: "#7a2e2e",
      primaryHover: "#5e2222",
      primaryForeground: "#ffffff",
      accent: "#b08d4f",
      accentForeground: "#211a0c",
      focusRing: "#b08d4f",
    },
    dark: {
      bg: "#1c1714",
      surface: "#241d19",
      surfaceRaised: "#2c2420",
      border: "#3a2f28",
      borderStrong: "#4d3f34",
      text: "#f2ede6",
      textMuted: "#c2b8ab",
      textFaint: "#8c8175",
      primary: "#b85c5c",
      primaryHover: "#c97575",
      primaryForeground: "#1c0e0e",
      accent: "#d9b676",
      accentForeground: "#241a08",
      focusRing: "#d9b676",
    },
  },

  moderno: {
    id: "moderno",
    label: "Moderno",
    description: "Tech-forward: indigo electrico, teal y grotesca de sistema.",
    radiusShape: "soft",
    fontDisplay: FONT_STACKS.grotesk,
    fontBody: FONT_STACKS.neutralSans,
    light: {
      bg: "#f7f8fa",
      surface: "#ffffff",
      surfaceRaised: "#ffffff",
      border: "#e1e4ea",
      borderStrong: "#c3c9d4",
      text: "#14161a",
      textMuted: "#5b6270",
      textFaint: "#9198a6",
      primary: "#3652e0",
      primaryHover: "#2b41b8",
      primaryForeground: "#ffffff",
      accent: "#16a6a0",
      accentForeground: "#ffffff",
      focusRing: "#3652e0",
    },
    dark: {
      bg: "#0e1116",
      surface: "#171b22",
      surfaceRaised: "#1e232c",
      border: "#2a303b",
      borderStrong: "#3a4150",
      text: "#e7e9ee",
      textMuted: "#a2a9b8",
      textFaint: "#6b7280",
      primary: "#7b8fff",
      primaryHover: "#95a5ff",
      primaryForeground: "#0a0e1a",
      accent: "#34d6ce",
      accentForeground: "#04211f",
      focusRing: "#7b8fff",
    },
  },

  minimalista: {
    id: "minimalista",
    label: "Minimalista",
    description: "Monocromo casi puro: el contenido es el unico protagonista.",
    radiusShape: "sharp",
    fontDisplay: FONT_STACKS.neutralSans,
    fontBody: FONT_STACKS.neutralSans,
    light: {
      bg: "#ffffff",
      surface: "#ffffff",
      surfaceRaised: "#ffffff",
      border: "#e7e5e1",
      borderStrong: "#cbc7c0",
      text: "#171717",
      textMuted: "#7a7873",
      textFaint: "#aeaba4",
      primary: "#171717",
      primaryHover: "#000000",
      primaryForeground: "#ffffff",
      accent: "#9a958a",
      accentForeground: "#171717",
      focusRing: "#171717",
    },
    dark: {
      bg: "#0a0a0a",
      surface: "#121212",
      surfaceRaised: "#181818",
      border: "#262626",
      borderStrong: "#383838",
      text: "#ededed",
      textMuted: "#a3a19b",
      textFaint: "#6f6d68",
      primary: "#ededed",
      primaryHover: "#ffffff",
      primaryForeground: "#121212",
      accent: "#aba496",
      accentForeground: "#0a0a0a",
      focusRing: "#ededed",
    },
  },

  oscuro: {
    id: "oscuro",
    label: "Oscuro",
    description:
      "Coctelera/steakhouse: nunca se aclara del todo, ambar sobre carbon incluso en modo claro.",
    radiusShape: "relaxed",
    fontDisplay: FONT_STACKS.grotesk,
    fontBody: FONT_STACKS.neutralSans,
    light: {
      bg: "#211d1a",
      surface: "#2a2521",
      surfaceRaised: "#332d28",
      border: "#413a33",
      borderStrong: "#554b41",
      text: "#f0e9e0",
      textMuted: "#bfb2a2",
      textFaint: "#877a6c",
      primary: "#c77d34",
      primaryHover: "#e0954a",
      primaryForeground: "#1a0f04",
      accent: "#8c2f2f",
      accentForeground: "#ffffff",
      focusRing: "#c77d34",
    },
    dark: {
      bg: "#121010",
      surface: "#1a1716",
      surfaceRaised: "#221e1c",
      border: "#2e2926",
      borderStrong: "#413a35",
      text: "#f2ece4",
      textMuted: "#c2b6a8",
      textFaint: "#8a7f72",
      primary: "#e0a050",
      primaryHover: "#eab568",
      primaryForeground: "#170f04",
      accent: "#a83d3d",
      accentForeground: "#ffffff",
      focusRing: "#e0a050",
    },
  },

  mediterraneo: {
    id: "mediterraneo",
    label: "Mediterráneo",
    description: "Costa: terracota, azul mar y cal blanca cálida.",
    radiusShape: "relaxed",
    fontDisplay: FONT_STACKS.slabSerif,
    fontBody: FONT_STACKS.neutralSans,
    light: {
      bg: "#f5f0e6",
      surface: "#ffffff",
      surfaceRaised: "#ffffff",
      border: "#e6dcc7",
      borderStrong: "#cfc0a0",
      text: "#2e2a1f",
      textMuted: "#7a7360",
      textFaint: "#aca384",
      primary: "#c1633d",
      primaryHover: "#a34f2f",
      primaryForeground: "#ffffff",
      accent: "#3a7ca5",
      accentForeground: "#ffffff",
      focusRing: "#3a7ca5",
    },
    dark: {
      bg: "#211d16",
      surface: "#2a251c",
      surfaceRaised: "#332c21",
      border: "#3f362a",
      borderStrong: "#544636",
      text: "#f0e9d8",
      textMuted: "#c1b69c",
      textFaint: "#8a7f66",
      primary: "#d98455",
      primaryHover: "#e69a6f",
      primaryForeground: "#1c0d04",
      accent: "#5fa0c9",
      accentForeground: "#04202e",
      focusRing: "#5fa0c9",
    },
  },

  premium: {
    id: "premium",
    label: "Premium",
    description: "Grafito y champan: contencion de materiales, no de color.",
    radiusShape: "soft",
    fontDisplay: FONT_STACKS.serif,
    fontBody: FONT_STACKS.neutralSans,
    light: {
      bg: "#f6f5f2",
      surface: "#ffffff",
      surfaceRaised: "#ffffff",
      border: "#e3e0d8",
      borderStrong: "#c8c3b5",
      text: "#1b1a18",
      textMuted: "#6e6a61",
      textFaint: "#a29c8e",
      primary: "#23211e",
      primaryHover: "#000000",
      primaryForeground: "#ffffff",
      accent: "#b9975b",
      accentForeground: "#221a08",
      focusRing: "#b9975b",
    },
    dark: {
      bg: "#121110",
      surface: "#1b1917",
      surfaceRaised: "#23201d",
      border: "#302c27",
      borderStrong: "#443e36",
      text: "#f1eee7",
      textMuted: "#bcb6a9",
      textFaint: "#847d70",
      primary: "#e3c892",
      primaryHover: "#edd8ab",
      primaryForeground: "#1c1408",
      accent: "#c9a96e",
      accentForeground: "#1c1408",
      focusRing: "#e3c892",
    },
  },
};

export const PRESET_LIST = Object.values(PRESETS);
